### PR TITLE
have igdx() find GAMS on its own

### PR DESCRIPTION
**Pull request by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q**
We had trouble with tests being skipped because the GDX libraries were not loaded correctly (see this [Mattermost discussion](https://mattermost.pik-potsdam.de/rd3/pl/6cjxsgayb7rdmdfwr5timwdejy)).

This code
https://github.com/pik-piam/gdx/blob/ab8fa071c4f0a358605a2a191a7426e725dd3c62/R/onLoad.R#L8-L17
will fail silently (more accurately: report `NULL`) when there are no elements containing "gams" on the path (which was the case here).

At least since version 1.0.2 the `gdxrrw` uses improved mechanisms to find GAMS on its own, see [here](https://github.com/GAMS-dev/gdxrrw/blob/64310f04e68f05d6bba2bd0159c81499a48898bc/gdxrrw/man/igdx.Rd#L26-L32).

So this change uses that instead.

Output of the fail state (with unloaded `gams` module on the cluster) looks like
```
gamsSysDir arg is empty: no GDX API there
Environment variable R_GAMS_SYSDIR not set: no GDX API there
Error loading the GDX API via the default shared library search mechanism
Could not load shared library libgdxdclib64.so: libgdxdclib64.so: cannot open shared object file: No such file or directory
LD_LIBRARY_PATH = /p/system/packages/R/4.1.2/gcc-mkl/lib64/R/lib:/p/system/packages/intel/oneapi/2021.1.1/mkl/2021.1.1/lib/intel6...
The GDX library has not been loaded
```

### CODE REVIEW

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
Crap.  This fails on the cluster in general. (While I cannot make it fail for me locally, so it seemed quite robust.)

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
Options would be:
1. Change to `igdx(Sys.getenv("GAMSROOT"))`, which is defined on the cluster.
2. `setenv R_GAMS_SYSDIR /p/system/packages/gams/…` in the `gams` module.
3. `append-path LD_LIBRARY_PATH /p/system/packages/gams/…` in the `gams` module.
4. Manually parse the `PATH`, which `igdx()` does on its own on Windows, but not on Linux.

**Comment by tscheypidi** [comment]
@0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q would it be an option to combine old and new methodology? Shouldn't that cover all known setups?

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
Sure, option 4.

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
Will do that.

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
I went with options 4 and 1.  We could do options 2 and 3 on the cluster as well.

**Review by tscheypidi — APPROVED** [review]

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
Fixed an [undocumented "feature" of `R CMD check`](https://github.com/pik-piam/gdx/actions/runs/7846038093/job/21439848141?pr=6#step:9:168), which fails if `packageStartupMessage()` passes anything containing the string "Error".

**Comment by pascal-sauer** [comment]
I noticed recently R 4.4 builds on windows on r-universe fail with the fail state output, see e.g. [here](https://github.com/r-universe/pik-piam/actions/runs/8465802541/job/23193505897#step:5:1439). Any ideas how to fix that @0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q ?

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
> R version 4.4.0 alpha (2024-03-26 r86209 ucrt)

Interesting choice …

R 4.3 would complain if `packageStartupMessage()` contained the string "Error", see [here](https://github.com/pik-piam/gdx/pull/6#issuecomment-1938236409).  So either try to find the part of the message that is offending R 4.4, or call `igdx()` only when it is actually needed (inside `readGDX()` and `writeGDX()`), not when the package is loaded.

**Pull request merged**
